// <auto-generated />
namespace DataAccessLayer_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Fİrstmigrations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fİrstmigrations));
        
        string IMigrationMetadata.Id
        {
            get { return "202202161910310_Fİrstmigrations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
